# Generated by Django 3.2 on 2022-11-05 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_room_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='base.topic'),
            preserve_default=False,
        ),
    ]
