# Generated by Django 3.2 on 2022-11-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
    ]
